name: astrid-tech
version: 0.1.0.0
github: "astralbijection/astrid.tech"
license: AGPLv3
author: "Astrid Yu"
maintainer: "astrid@astrid.tech"
copyright: "Astrid Yu"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/astralbijection/astrid.tech>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

internal-libraries:
  latg-db:
    source-dirs: latg/db/src
    dependencies:
      - aeson
      - text
      - time

  latg-graphql-lib:
    source-dirs: latg/graphql/src
    dependencies:
      - bytestring
      - morpheus-graphql
      - text

  latg-importer-lib:
    source-dirs: latg/importer/src
    dependencies:
      - aeson
      - bytestring
      - filepath
      - frontmatter
      - htoml
      - latg-db
      - text
      - time
      - uuid
      - vector
      - yaml

executables:
  latg-importer:
    main: Main.hs
    source-dirs: latg/importer/app
    dependencies:
      - latg-importer-lib

tests:
  latg-importer-test:
    main: Spec.hs
    source-dirs: latg/importer/test
    dependencies:
      - latg-importer-lib
