hType = "entry"
uuid = "f7f441b6-61cc-4eea-87e4-57190e6179eb"
name = "ZA WARUDO is not ending"
description = "TOML came out in 2013, so technically this is an anachronism."
createdDate = "2012-12-21T01:31:48.000Z"
publishedDate = "2012-12-21T01:31:48.000Z"
slug = [ 2021, 9, 24, 1 ]
