version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 8
    volumes:
      - ../..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/data/db

    # Uncomment to change startup options
    environment:
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: seams-dev

volumes:
  postgres-data:
