version: "3.7"
services:
  db:
    image: postgres:13.1
    env_file: .env.ci
    environment:
      POSTGRES_DB: astrid_tech_api
    ports:
      - 5432:5432

  sut:
    image: astridyu/astrid_tech_api_ci
    depends_on:
      - db
    env_file:
      - .env.ci
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: astrid_tech_api
    ports:
      - 18001:18001
    build:
      context: .
      dockerfile: Dockerfile-ci
      args:
        - INSTALL_DEV_DEPENDENCIES=1
    command: >
      bash -c "
        pipenv run python3 manage.py migrate &&
        pipenv run python3 manage.py test --keepdb
      "
