# A development database STRICTLY FOR DEVELOPMENT ONLY
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms
    ports:
      - 5432:5432

