name:                seams
version:             0.1.0.0
github:              "astralbijection/astrid.tech"
license:             AGPL-3
author:              "Astrid Yu"
maintainer:          "astrid@astrid.tech"
copyright:           "Astrid Yu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/astralbijection/astrid.tech#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- directory
- either
- filepath
- frontmatter
- lens
- MissingH
- mtl
- network-uri
- optparse-applicative
- persistent
- persistent-postgresql
- postgresql-typed
- servant
- text
- time
- transformers
- utf8-string
- uuid
- validation
- vector
- yaml

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  seams:
    main:                Main
    source-dirs:         app
    dependencies:
    - base >= 4.7 && < 5
    - seams

tests:
  seams-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - seams

    - raw-strings-qq
    - containers
    - filepath
    - hspec

