name: Periodic Upgrade

on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  upgrade-yarn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: false
          submodules: false

      - name: Run yarn upgrade
        run: yarn upgrade
        working-directory: astrid_tech_frontend

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: Automatic npm upgrades for ${{date}}"
          branch: auto-upgrade/npm
          force: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Upgrade npm packages
          branch: auto-upgrade/npm
          base: main

  upgrade-pip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Run pipenv update
        run: python -m pipenv update
        working-directory: astrid_tech_backend

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: Automatic pip upgrades for ${{date}}"
          branch: auto-upgrade/pip
          force: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Upgrade pip packages
          branch: auto-upgrade/pip
          base: main
